use crate::dispatch::engine_state::engine::*;
use dispatch_macros::auto_dispatch_from_enum;

#[repr(u32)]
#[derive(Debug, PartialEq, Copy, Clone)]
#[auto_dispatch_from_enum("generated/engine_ffi_signs.rs", "eng_body_")]
enum BodyCommand {
    GetType = 0,
    SetType = 1,
    IsStatic = 2,
    IsDynamic = 3,
    IsKinematic = 4,
    GetPosition = 5,
    SetPosition = 6,
    GetRotation = 7,
    SetRotation = 8,
    GetLinearVelocity = 9,
    SetLinearVelocity = 10,
    GetAngularVelocity = 11,
    SetAngularVelocity = 12,
    GetRestitution = 13,
    SetRestitution = 14,
    GetFriction = 15,
    SetFriction = 16,
    GetMass = 17,
    SetMass = 18,
    SetDamping = 19,
    IsSensor = 20,
    SetSensor = 21,
    IsActive = 22,
    SetActive = 23,
    IsSleeping = 24,
    SetSleeping = 25,
    ApplyForce = 26,
    ApplyImpulse = 27,
    ApplyTorque = 28,
    ClearForces = 29,
    GetCollisionGroup = 30,
    GetCollisionMask = 31,
    IsCcdEnabled = 32,
    SetCcdEnabled = 33,
    GetShapeType = 34,
    GetSphereRadius = 35,
    GetBoxHalfExtents = 36,
    GetHalfHeight = 37,
    GetShapeAxis = 38,
    GetComYOffset = 39,
}
